### DISCUSSION TITLE
Proposal: Add support for admission webhook

### DISCUSSION THREAD

**Discussion by felipeweb** [prest/prest#797] [API Server] [answered]
# Context

This is a proposal to add support for admission webhook in the same way that have in [Kubernetes](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/).

# Use cases

- As a developer I want to add a dynamic default values to my HTTP request and thus deliver a better customer experience.
- As a developer I want to add a dynamic validation to my HTTP request and thus deliver a better customer experience.

# Implementation idea

- Admission webhook servers must expose a HTTP POST endpoint;
- **Prestd** execute the post requests after all core middlewares;
- **Prestd** must convert XML requests and always send json to webhooks;
- A route can have multiple webhooks attached;
- If the route have multiple webhooks attached, it will be executed in the order that is declared in configuration;
- A mutation and validation webhook must be able to send and receive content like representations bellow;
- Body changes performed by a mutation webhook must be propagated to rest of the request

# Representations

## Errors

Any status code != 200 will be treated as error and response should follow representation bellow:

```json
{
    "error": "error message"
}
```

## Input for mutation and validation webhook

```json
{
    "database":"db name",
    "schema":"schema name",
    "table":"table name",
    "body":{
        "field1":"value1"
    }
}
```

## Output for mutation

```json
{
    "field1":"value1"
}
```

## Output for validation

If status code is 200 body will be ignored

# Configuration file example

```toml
[[admissionWebhooks]]
kind = "mutation"
database = "database name"
schema = "schema name"
table = "table name"
address = "http://localhost:9090/mutate"
verbs = [ "POST", "PATCH" ]

[[admissionWebhooks]]
kind = "validation"
database = "database name"
schema = "schema name"
table = "table name"
address = "http://localhost:9090/validation"
verbs = [ "POST", "PATCH" ]
```
