### ISSUE TITLE
Basic AUTH with JWT

### ISSUE THREAD

**Issue by tiaguinho** [prest/prest#276]
The idea is to have one endpoint with the basic implementation of authentication.
For example, we can configure the table, username and password fields.
```toml
[auth]
table = "users"
username = "email"
password = "password"
algorithm = "md5"
```

The configuration is an alias that prest will use to grant a JWT token.
