### ISSUE TITLE
EXECUTING SQL SCRIPTS,error

### ISSUE THREAD

**Issue by moziie** [prest/prest#605]
Deploy using Docker
when I test the 'EXECUTING SQL SCRIPTS'
 sh curl -X POST "http://localhost:3000/_QUERIES/data/update" -d '{"name":"test"}'
{
        "error": "could not get script data/update, could not load /home/fanwu/queries/data/update.write.sql"
}

##the sql file I wrote is here:
ll /home/fanwu/queries/data/update.write.sql
-rw-r--r--. 1 root root 131 9月  15 14:50 /home/fanwu/queries/data/update.write.sql
##the Configuration file:
sh:  grep "queries" prest.toml 
[queries]
location = "/home/fanwu/queries/"
——————————————————
I want to know what went wrong and why the file could not be loaded.
please help me,Thanks

**Comment by avelino** [comment]
Which version are you using?

binary/docker or branch main

**Comment by moziie** [comment]
Docker used，and the command is :
docker run -d -p 3000:3000 --network=host -e PREST_PG_URL=postgres://postgres:75hne63@127.0.0.1:5432/fanwu?sslmode=disable -e PREST_DEBUG=true prest/prest:v1

**Comment by avelino** [comment]
This problem has been corrected in this contribution, but a version with the correction of this problem has not yet been generated #602

I will release it in the next few days - sorry

**Comment by avelino** [comment]
@george-silva I usually use the official prest image in docker-compose, the example below is a project in production

```
  prest:
    image: prest/prest:latest
    container_name: "prest"
    restart: always
    links:
      - "postgres:postgres"
    volumes:
      - "./etc/prest:/app/guiame"
    environment:
      - PREST_CONF=/app/guiame/prest.toml
      - PREST_MIGRATIONS=/app/guiame/migrations
      - PREST_QUERIES_LOCATION=/app/guiame/queries
      - PREST_PG_HOST=postgres
      - PREST_PG_DATABASE=...
      - PREST_PG_USER=...
      - PREST_PG_PASS='...'
      - PREST_PG_SINGLE=false
      - PREST_SSL_MODE=disable
    depends_on:
      - postgres
```
