### ISSUE TITLE
net::ERR_CONNECTION_REFUSED from fetch

### ISSUE THREAD

**Issue by crisclacerda** [prest/prest#674]
Just followed the documentation, cloned the repo and used go run to started prest.
I can make the example request 'first call to api': 

`curl -i -X GET http://127.0.0.1:3000/databases -H "Content-Type: application/json"
`

But when trying to do the same from the browser using fetch

` fetch('http://127.0.0.1:3010/databases', {
    method: 'GET',
    headers: new Headers({
    'Content-Type': 'application/json'
    })
}).then((response) => {
      return response.json();
    }) .then((data) => {
      console.log('data')
})
`
I get net::ERR_CONNECTION_REFUSED and don't see a thing on the console running prest..
Here is my prest.toml

```
debug = true
[jwt]
default = false
[auth]
enabled = false
[ssl]
mode = "disable"
[cors]
alloworigin = ["http://127.0.0.1:8080/*"]
allowheaders = ["GET", "DELETE", "POST", "PUT", "PATCH", "OPTIONS"]
```

**Comment by arxdsilva** [comment]
@crisclacerda on the first curl you're using port `3000` and in the second you're using `3010`, which is not where the db is running, that is why you get this error.

**Comment by crisclacerda** [comment]
dam lmao;
sorry for bothering with this. but thanks for the catch!

**Comment by crisclacerda** [comment]
That's not really issue thought. It was just typo as I copied the example.
prest is in fact running on 3010.

`curl -i -X GET http://127.0.0.1:3010/databases -H "Content-Type: application/json"
HTTP/1.1 200 OK
...`

**Comment by avelino** [comment]
test using the latest beta version of prestd and it worked, in this version we fixed a bug in the CORS support (read more here #675).

this is the beta version docker image, version v1.0.15 will be generated soon
```
ghcr.io/prest/prest:beta
```

**request:**
```http
curl -i -X GET http://127.0.0.1:3000/databases -H "Content-Type: application/json"
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Wed, 26 Jan 2022 21:26:58 GMT
Content-Length: 47
```
**response:**
```json
[{"datname":"postgres"},
 {"datname":"prest"}]
```
**toml:**
```toml
debug = true
[jwt]
default = false
[auth]
enabled = false
[ssl]
mode = "disable"
[cors]
alloworigin = ["*"]
allowheaders = ["Content-Type"]
allowmethods = ["GET", "DELETE", "POST", "PUT", "PATCH", "OPTIONS"]
```

**docker compose:**
```yaml
  prestd:
    image: ghcr.io/prest/prest:beta
    links:
      - "postgres:postgres"
    environment:
      - PREST_AUTH_ENABLED=false
      - PREST_PG_HOST=postgres
      - PREST_PG_USER=prest
      - PREST_PG_PASS=prest
      - PREST_PG_DATABASE=prest
      - PREST_PG_PORT=5432
      - PREST_SSL_MODE=disable
    volumes:
      - "./prest.toml:/app/prest.toml"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
```
