### ISSUE TITLE
CORS: implementation problem (confusion)

### ISSUE THREAD

**Issue by avelino** [prest/prest#675]
```
Access to fetch at 'http://127.0.0.1:3000/prest/public/testando?id=$eq.1' from origin 'http://127.0.0.1:3001' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```

prestd config:
```toml
[cors]
alloworigin = ["*"]
allowheaders = ["GET", "DELETE", "POST", "PUT", "PATCH", "OPTIONS"]
```

## problem

there is a misunderstanding in the implementation of cors, we are using headers as methods, see an example of a valid request

```http
OPTIONS /resource/foo
Access-Control-Request-Method: GET
Access-Control-Request-Headers: Content-Type, x-requested-with
Origin: https://foo.bar.org
```

[learning more](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers)

## solution

The cors permission configuration must contain 3 variables:
- `origin`
- `header` - today we are passing methods not headers
- `method` **<- not yet implemented**

```toml
[cors]
alloworigin = ["*"]
allowheaders = ["Content-Type"]
allowmethods = ["GET", "DELETE", "POST", "PUT", "PATCH", "OPTIONS"]
```
