### ISSUE TITLE
Docker-compose - dial tcp: lookup host.docker.internal on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by vmesel** [prest/prest#743]
This is not a pREST problem, but a networking problem when using SSH Tunnelling to access a database. I'm adding this issue so users can handle it if it happens to occur to them.

Docker-compose.yml

```
version: "3"
services:
  prest:
    image: prest/prest:latest
    env_file:
      - .env
    volumes:
      - "./queries/:/app/queries/"
      - "./prest_conf/prest.toml:/app/prest.toml"
    ports:
      - 8081:8081
```

Container log:

```
test_prest-prest-1  | [prestd] Waiting for port host.docker.internal:5433 to become available...
test_prest-prest-1  | [prestd] Plugin/build: starting...
test_prest-prest-1  | [prestd] Go build simple plugins in only file!
test_prest-prest-1  | go build: hello plugin...
test_prest-prest-1  | [prestd] Go build complex plugins in folder (with main.go file)!
test_prest-prest-1  | [prestd] Plugin/build: ending
test_prest-prest-1  | [prestd] Ready hosting host.docker.internal to port 5433 !
test_prest-prest-1  | 2022/11/23 17:03:29 [warning] adapter is not set. Using the default (postgres)
test_prest-prest-1  | 2022/11/23 17:03:29 [error] dial tcp: lookup host.docker.internal on 127.0.0.11:53: no such host
```

This error is caused by docker's networking settings on your computer, to solve this add this single line to your service specification on docker-compose.yml

```
network_mode: host
```
